name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize, labeled]

jobs:
  check:
    name: Checking required reviews
    runs-on: ubuntu-latest

    # GitHub should provide a "pull_request_review_target", but they don't and
    # the action will fail if run on a forked PR.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    
    steps:
      - uses: mhryshkin/action-required-review@v2.4.0
        with:
          token: ${{ secrets.VALUE }}
          skipOnLabels: |
           - hotfix
          requirements: |
           - paths: unmatched
             teams:
              - two-of:
                  - selfish-team
                  - dream-team
