name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  run: |
    echo "This token is masked: ${TOKEN}"
env: 
  TOKEN: ${{ github.TOKEN }}
